[project]
name = "ai-dial-chat-completions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aidial-client>=0.3.0",
    "dotenv>=0.9.9",
    "requests>=2.32.5",
]
